### ISSUE TITLE
Missing Licenses?

### ISSUE THREAD

**Issue by VRichardJP** [ataparlar/loam-mapper#4]
It looks like this project includes snippets from existing open source projects. For example:

https://github.com/ataparlar/loam-mapper/blob/51946ff596075636c1991c58815b6869738a60bc/src/feature_extraction.cpp#L63-L98

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/blob/896a7a95a8bc510b76819d4cc48707e344bad621/LeGO-LOAM/src/featureAssociation.cpp#L643-L678

It would be nice to mention their work and add their license :)

**Comment by ataparlar** [comment]
Yes. You are right. I forgot to add licenses and mention their work. 

I added the licenses in this commit:
[https://github.com/ataparlar/loam-mapper/tree/876f37c917c093bb2f1aff6e8a51d7fa48c96824](https://github.com/ataparlar/loam-mapper/tree/876f37c917c093bb2f1aff6e8a51d7fa48c96824)
I also added papers to the readme. Thank you for your provide
